package com.neuronrobotics.bowlerbuilder.model.tree.groovy.ast;

/**
 * Enum of all {@link ASTNode} types.
 */
public enum ASTNodeType {

  RootNode, //Special type for roots of an AST
  ArgumentListNode,
  ArrayNode,
  AssertNode,
  AttributeNode,
  BinaryNode,
  BitwiseNegationNode,
  BlockNode,
  BooleanNode,
  BreakNode,
  BytecodeNode,
  CaseNode,
  CastNode,
  CatchNode,
  ClassDeclarationNode,
  ClassExpressionNode,
  ClosureListNode,
  ClosureNode,
  ConstantNode,
  ConstructorCallNode,
  ContinueNode,
  DeclarationNode,
  DoWhileNode,
  ExpressionNode,
  FieldNode,
  ForNode,
  GStringNode,
  IfElseNode,
  ListNode,
  MapEntryNode,
  MapNode,
  MethodCallNode,
  MethodNode,
  MethodPointerNode,
  NotNode,
  PostfixNode,
  PrefixNode,
  PropertyNode,
  RangeNode,
  ReturnNode,
  ShortTernaryNode,
  SpreadMapNode,
  SpreadNode,
  StaticMethodCallNode,
  SwitchNode,
  SynchronizedNode,
  TernaryNode,
  ThrowNode,
  TryCatchFinallyNode,
  TupleNode,
  UnaryMinusNode,
  UnaryPlusNode,
  VariableNode,
  WhileNode

}
