language: java

matrix:
  fast_finish: true
  include:
    - os: linux
      jdk: openjdk8
    - os: osx
      osx_image: xcode8.3
env:
  - TERM=dumb

before_install:
  - sudo apt install -y libopenjfx-java=8u161-b12-1ubuntu2 libopenjfx-java-doc=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2 openjfx=8u161-b12-1ubuntu2
install:
  - ./gradlew assemble --stacktrace

script:
  - ./gradlew check jacocoTestReport --stacktrace -PlogTests -Pheadless

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
