language: java
install:
  - sudo add-apt-repository ppa:cwchien/gradle -y
  - sudo apt-add-repository ppa:webupd8team/java -y
  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty universe multiverse"
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes gradle libopencv2.4-jni  libopencv2.4-java
  - sudo updatedb
  
script:
  - locate opencv-24|grep .jar
  - export OPENCV_DIR=/usr/share/OpenCV/
  - gradle compileJava jar javadoc test 
cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

# for running tests on Travis CI container infrastructure for faster builds
sudo: true
dist: trusty
