language: java
install: 
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes libopencv2.4-java
  
script: 
  - ./gradlew compileJava jar javadoc test 
cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

# for running tests on Travis CI container infrastructure for faster builds
sudo: true
