language: java
install: 
  - sudo add-apt-repository ppa:cwchien/gradle -y
  - sudo apt-add-repository ppa:webupd8team/java -y
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes gradle libopencv2.4-java oracle-java8-installer oracle-java8-set-default
  
script: 
  - ./gradlew compileJava jar javadoc test 
cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

# for running tests on Travis CI container infrastructure for faster builds
sudo: true
