
version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat spotlessApply --info --no-daemon
  - gradlew.bat assemble --info --no-daemon

test_script:
  - gradlew.bat check --info --no-daemon

branches:
  only:
    - master

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: true
